# Colors (Adwaita Light)

# Default colors
[colors.primary]
background = '#ffffff'
foreground = '#2e3436'

# Normal colors
[colors.normal]
black   = '#241f31'
red     = '#c01c28'
green   = '#26a269'
yellow  = '#e5a50a'
blue    = '#1c71d8'
magenta = '#813d9c'
cyan    = '#2ec27e'
white   = '#deddda'

# Bright colors
[colors.bright]
black   = '#5e5c64'
red     = '#ed333b'
green   = '#33d17a'
yellow  = '#f5c211'
blue    = '#3584e4'
magenta = '#9141ac'
cyan    = '#4fd2fd'
white   = '#ffffff'
